# case-insensitive matching only if there are no case-sensitive matches
# see https://superuser.com/a/1092328
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

################################################################################
## git
################################################################################
gl() { git log --pretty='%h%%%s%%%cr' -n${1:-5}|column -t -s'%' }
_gl() { words[1]=(git log); (( CURRENT+=1 )); service=git; _git }

glh() { git rev-parse --short $1|pbcopy }
compdef _gl glh

glm() { git show -s --format=%s $1|pbcopy }
compdef _gl glm

gia() {
    if (( $# > 0)); then
        if (( $# == 1 )) && [[ "$1" == . ]]; then
            git add --verbose .
        else
            git add --verbose ${@}
        fi
    else
        git status --porcelain|grep "^.[^\ ]"|fzf -m --bind ctrl-a:toggle-all|sed "s/...//"|xargs git add --verbose
    fi
}
_gia() { words[1]=(git commit); (( CURRENT+=1 )); service=git; _git }
compdef _gia gia

gir() {
    if (( $# > 0)); then
        if (( $# == 1 )) && [[ "$1" == . ]]; then
            git restore --staged $(git diff --staged --name-only)
        else
            git restore --staged ${@}
        fi
    else
        git diff --staged --name-only|fzf -m --bind ctrl-a:toggle-all|xargs git restore --staged
    fi
}

gbs() { git switch $1 2&>/dev/null || git switch --create $1 }
_gbs() { words[1]=(git branch); (( CURRENT+=1 )); service=git; _git }
compdef _gbs gbs

gc() {
    if (( $# == 1 )); then
        if [[ "$1" == . ]]; then
            git commit --amend
        else
            git commit -m "$1"
        fi
    else
        git commit
    fi
}
_gc() { words[1]=(git commit); (( CURRENT+=1 )); service=git; _git }
compdef _gc gc

gri() {
    if (( $# == 1 )); then
        if [[ "$1" =~ '^[0-9]+$' ]]; then
            git rebase -i "HEAD~$1"
        else
            git rebase -i "$1"
        fi
    else
        git rebase -i $(gl 15|fzf|cut -f1 -d' ')
    fi
}
_gri() { words[1]=(git rebase -i); (( CURRENT+=2 )); service=git; _git }
compdef _gri gri

gpu() { git push --set-upstream $1 $(git branch --show-current) }
_gpu() { words[1]=(git remote show); (( CURRENT+=2 )); service=git; _git }
compdef _gpu gpu

gig() { curl -sL "https://www.toptal.com/developers/gitignore/api/$1" }
_gig() { _values -s , $(curl -sL 'https://www.toptal.com/developers/gitignore/api/list?format=lines') }
compdef _gig gig

alias gqc='gia && git commit'
alias gs='git status'
alias gp='git push'
alias gr='git rebase'
alias gg='git pull'
alias ggr='git pull -r'
alias gbl='git branch'
alias gblr='git branch --remotes'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gbm='git branch -m'
alias gbM='git branch -M'
alias gbrh='git reset --hard'

################################################################################
## nix
################################################################################
nix-store-path() { echo "$(readlink -f ${$(command -v $1):-$1})" }
nix-store-derivation() { nix-store --query --deriver "$(nix-store-path $1)" }
nix-store-dependencies() { nix-store --query --references "$(nix-store-path $1)" }
nix-store-references() { nix-store --query --referrers "$(nix-store-path $1)" }

################################################################################
## misc
################################################################################
cheat() {curl "https://cheat.sh/${@}"|bat}
